### ISSUE TITLE
InputFunctionException in line 397 of /home/alex/Hiprfish/hiprfish/probe-design/hiprfish-probe-design-consensus/Snakefile: AttributeError: 'DataFrame' object has no attribute 'THEMECOLOR'

### ISSUE THREAD

**Issue by Thinking-about-Systems** [proudquartz/hiprfish#1]
Hello, 

Hoping to get some guidance on your probe design pipeline. 

When I run the code I get this error:

**InputFunctionException in line 397 of /home/alex/Hiprfish/hiprfish/probe-design/hiprfish-probe-design-consensus/Snakefile:
AttributeError: 'DataFrame' object has no attribute 'THEMECOLOR'
Wildcards:
design_id=CallMe_HOMD**

If I add the following to the simulation table:

**THEMECOLOR | HELPER_PROBE_REPEAT | OT_GC_CUTOFF | MT_CUTOFF | SOD | BITSCORE_THRESH | DNACONC**

The code will proceed and then breakdown here

![image](https://user-images.githubusercontent.com/78146047/118571037-4a2faa00-b74b-11eb-85f8-07c2e6106c08.png)

Should values be appended to the simulation table at some point in the pipeline that is not being written causing the code to error? 

Thanks! 
Alex

**Comment by Thinking-about-Systems** [comment]
Hold that thought. Might be an issue with my blastdb

**Comment by proudquartz** [comment]
Hi Alex - it looks like the blast command is having trouble finding the reference database. If you downloaded the 16SMicrobial database from NCBI and put in the *folder* /home/alex/Hiprfish/Resources/16SMicrobial, your reference database file path should be /home/alex/Hiprfish/Resources/16SMicrobial/16SMicrobial in order for blast to find it. Try this and see if it works!

**Comment by Thinking-about-Systems** [comment]
Thanks for the speedy reply! 

I fixed that and now I have the following error

![image](https://user-images.githubusercontent.com/78146047/118572282-0e4a1400-b74e-11eb-945b-55fae2f370b5.png)

**Comment by proudquartz** [comment]
My best guess is that blast tried initiated a output filehandle in the utilities directory while it tried to blast the input fasta file against the 16SMicrobial database, but failed to do so last time because it couldn't find the blast database. Try removing the `{input_filename}.fasta.blast.out` file in the `/{sample_dir}/utilities` directory, and try running the snakemake again.

**Comment by Thinking-about-Systems** [comment]
Seems to progress a bit farther now. I'm getting a PermissionError and a KeyError 
P.S. attempting to run this on the windows linux subsystem (wsl2). 

![image](https://user-images.githubusercontent.com/78146047/118580181-70f6dc00-b75d-11eb-8d47-ee1f0a2ca132.png)
![image](https://user-images.githubusercontent.com/78146047/118580209-8409ac00-b75d-11eb-8570-814880fd6b6e.png)

**Comment by proudquartz** [comment]
hmm seems like usearch cannot write to your directory? I don't have experience with running on wsl2, so I am not sure if I have anything useful to suggest on that front. Maybe try directly running the usearch command on a terminal and see if you get the same PermissionError?

**Comment by Thinking-about-Systems** [comment]
I don't think that is it. I end up with the oriented pacbio file and there is also an output file in the consensus folder.

![image](https://user-images.githubusercontent.com/78146047/118584352-c2569980-b764-11eb-8d50-0722a8d15d8e.png)
![image](https://user-images.githubusercontent.com/78146047/118584375-cd112e80-b764-11eb-9a14-0c2bf3449e90.png)
![image](https://user-images.githubusercontent.com/78146047/118584426-e3b78580-b764-11eb-946b-866cbce4c4e9.png)

Do you think there could be something wrong with my input csv file? 

Here is what that looks like
![image](https://user-images.githubusercontent.com/78146047/118586262-6f7ee100-b768-11eb-9c27-412ee59bd9fb.png)

**Comment by Thinking-about-Systems** [comment]
I also noticed that you have some of that your file paths appear in the hiprfish_design_probes.py file
![image](https://user-images.githubusercontent.com/78146047/118588335-2fb9f880-b76c-11eb-89da-aa503df78c1a.png)

The paths are found in lines 81, 101,  247, and 264. I saw on your old commit for the probe-design-consensus from 2019 that the paths were fixed so I copied the hiprfish_design_probes.py file from there. Might be an issue there. Seems the latest version is updated compared to the last version.

**Comment by proudquartz** [comment]
Ah yes - the paths should be changed to wherever you have installed usearch. The '/home/hs673/Tools/usearch' is the path to the usearch executable on the machine I was using. You would need to change it to a path that is on your system. Let me know if this helps!

**Comment by Thinking-about-Systems** [comment]
I noticed you imported the glob function in the hiprfish_select_probes.py script but the function is not called anywhere in the script. Is it possible pytables can't read the h5 evaluation file causing the math domain error?

**Comment by Thinking-about-Systems** [comment]
Hi Hao,

Changing the Na=Na to Na=390 in line 210 of the select probes script avoided the math domain error. The pipeline goes to 97% completion and then fails to generate the full probe sequences. 

Here is what the error looks like: 
![image](https://user-images.githubusercontent.com/78146047/119220355-21dfdc80-bab8-11eb-85e7-c277673c8164.png)

Any guidance is much appreciated!

**Comment by Thinking-about-Systems** [comment]
Hi Hao, 

I was able to complete the probe design consensus using a different sample community. We are excited to try it out on our oral communities!

I just wanted to mention that I needed to add the following inputs to the simulation CSV in order to complete the design. They are as follows: THEMECOLOR, HELPER_PROBE_REPEAT, OT_GC_CUTOFF, DNACONC, BITSCORE, SOD, and MT_CUTOFF.

**Comment by proudquartz** [comment]
Hey sorry for the late response - got swamped the past few days.

Glad you got it to work! I will update the repo. Looking forward to seeing what you folks find in your communities :)
