### ISSUE TITLE
error in rule design_probes

### ISSUE THREAD

**Issue by MiriJ15** [proudquartz/hiprfish#2]
Hi Hao,

I was using your pipeline design and it was working flawlessly, but for some reason, after few repeats I have started getting this error (screenshot below) and I cannot figure out what is causing it. So far I have tried reinstalling environment, different nucleotide sequences and databases. Nonetheless, this problem still persists. Have you encountered this issue by any chance?

Best,
Mir-Mammad.

<img width="2033" alt="Screen Shot 2022-02-14 at 3 56 00 PM" src="https://user-images.githubusercontent.com/86243044/153946263-cfa9254f-febb-4593-8bb3-bd82819efd5d.png">

**Comment by proudquartz** [comment]
Hello Mir-Mammad,

I have not encountered this specific bug before, but it looks like usearch
is not happy with the computer architecture that you have. The key phrase
in the error output is "Bad CPU type in executable:
'/Users/valmlab/Desktop/HIPRFISH2/usearch11.0.667_i86osx32". I am not
exactly sure how to debug it, but my suggestion would be to perhaps
re-download the usearch executable or try on a different computer, and make
sure that you can run usearch on a terminal independent of the pipeline.

**Comment by MiriJ15** [comment]
Thank you for prompt reply. You were right the issue was related to the usearch as latest macOS does not support 32 bit applications anymore. Was the pipeline designed for 32 or 64 bit systems?

**Comment by proudquartz** [comment]
I was running this version mostly on HPC clusters, which I believe were
64-bit. I just checked the usearch website and it seems like the free
32-bit version works on both 32-bit and 64-bit machines. I have to say I am
not sure what the best thing to do is with the new mac being not compatible
with 32-bit applications.

**Comment by YeshuaOfNazareth** [comment]
I have installed ubuntu and no longer get "Bad CPU error", so I guess 32 bit .exe was the reason why I did not manage to run back then. Now I am getting an error related to primer 3 (I assume). I have reinstalled primer 3 in different ways, but I guess there is another issue related to it. Could you please explain me what does this error code mean?
![image](https://user-images.githubusercontent.com/86243044/154828300-e6877f19-7e1a-4fed-abe1-edae1b4f4b2e.png)
