### ISSUE TITLE
FASTA file

### ISSUE THREAD

**Issue by FraMont1** [proudquartz/hiprfish#4]
Hi Dr. Shi,
Thanks for developing HiPR-FISH, this is an amazing tool.
I followed your tutorial, and I was able to run the whole hiprfish-probe-design-consensus pipeline (using the hiprfish_config_example.json file).

Now I would like to run the same pipeline using my own data as input. 
For the .fasta file in input I downloaded the 16S rRNA sequences for 4 different bacteria (A, B, C, D).

The bacterium A has 3 genes annotated as 16S rRNA. I performed a Multiple Sequence Alignment for the 16S rRNA sequences and the result shows that the nucleotide sequences of these 3 genes are identical, so I used only 1 sequence as input in the .fasta file.
The bacterium B has 4 genes annotated as 16S rRNA. I performed a Multiple Sequence Alignment for the 16S rRNA sequences and the result shows that the nucleotide sequences of these 4 genes are identical, so I used only 1 sequence as input in the .fasta file.
The bacterium C has 9 genes annotated as 16S rRNA. I performed a Multiple Sequence Alignment for the 16S rRNA sequences and the result shows that the nucleotide sequences of these 9 genes show that 8 genes are identical, but 1 gene has two SNPs. 
The bacterium D has 4 genes annotated as 16S rRNA. I performed a Multiple Sequence Alignment for the 16S rRNA sequences and the result shows that the nucleotide sequences of these 4 genes show that all these genes are different with different SNPs and 1 insertion.

I would like to ask you: 
1)	Is it correct to use only one 16S rRNA FASTA sequence as input for the bacteria A and B or I have to use all the 16S rRNA FASTA sequences?
2)	For the bacterium C should I use two 16S rRNA FASTA sequences (1 for the 7 genes that are identical and 1 for the gene that has the 2 SNPs)?
3)	For the bacterium D should I use all the for 16S rRNA FASTA sequences?
4)	In case I have to use all the four 16S rRNA FASTA sequences for the bacterium D, two 16S rRNA FASTA sequences for the bacterium C, one 16S rRNA FASTA sequence for the bacterium A, and one 16S rRNA FASTA sequence for the bacterium B, is it correct to use only one FASTA file as input or I have to run the pipeline four time (one with the 16S rRNA FASTA sequence of the bacterium A, one with the 16S rRNA FASTA sequence of the bacterium B, one with the 16S rRNA FASTA sequences of the bacterium C, one with the 16S rRNA FASTA sequences of the bacterium D)?

I am sorry for all this questions, but I really did not understand this point.

Thank you for your answer.

Best regards,
Francesco

**Comment by proudquartz** [comment]
Hi Francesco,

Apologies for missing your initial post. You can use multiple 16S sequence for each species. In cases where there are subtle differences between 16S sequences within a species, it is probably better to include all the different sequences so that the probes you design can cover all the different versions of the rRNA that may be present in the cells. Hope this helps!

Hao

**Comment by FraMont1** [comment]
Thank you for your answer, this is very useful!
